export const estadosList = [
    { label: "Aguascalientes", value: "AG" },
    { label: "Baja California", value: "BC" },
    { label: "Baja California Sur", value: "BS" },
    { label: "Campeche", value: "CC" },
    { label: "Chiapas", value: "CS" },
    { label: "Chihuahua", value: "CH" },
    { label: "Ciudad de México", value: "DF" },
    { label: "Coahuila", value: "CL" },
    { label: "Colima", value: "CM" },
    { label: "Durango", value: "DG" },
    { label: "Guanajuato", value: "GT" },
    { label: "Guerrero", value: "GR" },
    { label: "Hidalgo", value: "HG" },
    { label: "Jalisco", value: "JC" },
    { label: "Edo. Méx", value: "MC" },
    { label: "Michoacán", value: "MN" },
    { label: "Morelos", value: "MS" },
    { label: "Nayarit", value: "NT" },
    { label: "Nuevo León", value: "NL" },
    { label: "Oaxaca", value: "OC" },
    { label: "Puebla", value: "PL" },
    { label: "Querétaro", value: "QO" },
    { label: "Quintana Roo", value: "QR" },
    { label: "San Luis Potosí", value: "SP" },
    { label: "Sinaloa", value: "SL" },
    { label: "Sonora", value: "SR" },
    { label: "Tabasco", value: "TC" },
    { label: "Tamaulipas", value: "TS" },
    { label: "Tlaxcala", value: "TL" },
    { label: "Veracruz", value: "VZ" },
    { label: "Yucatán", value: "YN" },
    { label: "Zacatecas", value: "ZS" },
]